### ISSUE TITLE
some issues on particle_system_effects_Godot3 

### ISSUE THREAD

**Issue by Didifred** [danilw/godot-utils-and-other#6]
First thanks a lot to share these cool particule effects !

I've experiment some crashes without so much error log eitheir in editor clicking on  cube_o ,cube and demo_p nodes or running the appli with "Socket close .. " error message. => So i suppress this nodes, and it's OK.

My GPU is quite old ... NV GeForce GT 630M, but i tried on more recent hw with NV Quatro and still some of the previous nodes crash the execution. What could be the issues ? Is it openGL drivers that are buggy ? How work ES 3.0 emulation on PC based on standard OpenGL, is it included in Godot ?

**Comment by danilw** [comment]
just checked... no crashes at all(in Linux)
my Godot version is Godot 3.2.2 stable and Godot 3.2.4 beta4
I tested this project on Nvidia 750 and Vega8 integrated (both 2Gb VRAM) no crashes...
**il check tomorrow on Windows**

> First thanks a lot to share these cool particule effects !

thanks but... I warn you that every project I made here is just a "weird test-experiment"(that I use for my own learning graphic stuff) with some problems that you have to fix... (I did not know ways to make it correct at a time making these projects or I misunderstand something...)(as an example in this `particle_system_effects_Godot3` I send camera position as my own uniform...when it should not be like this)... also code in projects is not good for "understanding/learning" but this is not tutorials - it up to you if you want to spend your time understanding my code...

**Comment by Didifred** [comment]
I'm on Windows too. No problem at all for me, i just feel to give you feedback can ne useful for you.

I think it dépends on the background knowledge, in my case i know gles 3.0 ans GLSL shaders, but not particules techniques. Since i have a Godot game in progress, it give somme ideas for effect.

**Comment by danilw** [comment]
> I'm on Windows too. No problem at all for me

wait I dont understand, 

> My GPU is quite old ... NV GeForce GT 630M, but i tried on more recent hw with NV Quatro and still some of the previous nodes crash the execution. What could be the issues ?

is not this project `particle_system_effects_Godot3` crash in editor for you?

does it work outside of editor? https://danilw.itch.io/particle-effects-godot3 from exe or web-version?

what you Godot version?

**Comment by Didifred** [comment]
> > I'm on Windows too. No problem at all for me
> 
> wait I dont understand,

Sorry for the confusion, when i say 'no problem at all' it was relative to your warnings relative what you qualify as sandbox tests.
 
> > My GPU is quite old ... NV GeForce GT 630M, but i tried on more recent hw with NV Quatro and still some of the previous nodes crash the execution. What could be the issues ?
> 
> is not this project `particle_system_effects_Godot3` crash in editor for you?
> 
> does it work outside of editor? https://danilw.itch.io/particle-effects-godot3 from exe or web-version?
> 
> what you Godot version?

So yes it is `particle_system_effects_Godot3` that crash on the editor and fails to execute in exe version.
I use 3.2.3 stable and test as well on 3.2.2 stable.

**Comment by danilw** [comment]
I tested on Windows Nvidia 750 drivers version 456.71
everything work
(also before releasing I tested it on multiple PC and  receive feedback from other people-it works for them also)
![1](https://user-images.githubusercontent.com/24825887/105432734-455d5c80-5c69-11eb-993c-dbb83c1df4c0.png)

*I can guess* your crash may come because of "too much Vram usage"... `particle_system_effects_Godot3` in the Godot editor use 800Mb Vram, and exe or web version use more than 600Mb

> and fails to execute in exe version.

I 100% sure that shaders there is correct(I report more than 5 driver bugs writing those shaders(lots of time wasted on debug drivers), so I literally 100% sure about it I did dodge every driver bug), and Godot GLES3 render are fine.

can you say **what console output(browser console(F12)) you have launching web version** https://danilw.itch.io/particle-effects-godot3 on page? if it crashes on web it 99% problem in your GPU or drivers, it still may be problem in Godot render

And can you please try launching this https://danilw.itch.io/cubes-experiment (in web or exe) this is even more complex shaders and scene but in GLES2(Godot GLES2 mode), does it work for you?

**Comment by Didifred** [comment]
Making invisible the demo_p/cube node make it works.
so i make a little test simplyfying the fragment shader of "particle_cube_base.shader" with a constant fragment, no more crash.

So i conclude it is a gpu driver bug :
NVIDIA Quadro K1100M/PCIe/SSE
Version pilote 341.49.
25/02/2015

**Comment by danilw** [comment]
341.49
its very old driver, I know it "technically" supported because  its old generation of GPU (and it close source driver...)
but I do not have the hardware to test my shaders there

so I do not know about this old driver problems sorry :(

> so i make a little test simplyfying the fragment shader of "particle_cube_base.shader" with a constant fragment, no more crash.

easy way to test - you can try to make empty godot project, add 3dmesh instanse make quad, make shader material and copy paste this code to shader there [particle_lineGlow_base.shader](https://github.com/danilw/godot-utils-and-other/blob/master/particle_system_effects_Godot3/shaders/particle_lineGlow_base.shader)

and look if it crashes

**Comment by Didifred** [comment]
The particle lineGlow_base.shader works Ok, addionnally i replace code of particle_cube_base.shader file by the particle_lineGlow_base code, and like expected no more crash.
I close this issue since issues are related to Nvidia drivers. 
Thanks

**Comment by danilw** [comment]
okey thanks for report, il add note about this problem on old drivers

you can ask me anything about my projects in discord if you need https://discord.gg/JKyqWgt
